//this is derived from the ConfigurationA.i file
// pin names derived from 100-lead LQFP SAM3A4/8C and SAM3X4/8C Pinout datasheet
#define UI_DISPLAY_RS_PIN 8 // PC22
#define ORIG_X_MIN_PIN 11 // PD7
#define ORIG_Y_DIR_PIN 12 // PD8
#define TEMP_0_PIN 65 // PB20 ADC13
#define TEMP_1_PIN 126(52) // PB21 ADC14
#define ORIG_X_DIR_PIN 14 // PD4
#define ORIG_X_STEP_PIN 15 // PD5
#define HEATER_0_PIN 16 // PA13
#define LIGHT_PIN 17 // PA12
#define FIL_SENSOR1_PIN 24 // PA15
#define ORIG_FAN_PIN 25 // PD0
#define ORIG_X_ENABLE_PIN 29 // PD6
#define ORIG_Y_STEP_PIN 30 // PD9
#define UI_DISPLAY_D0_PIN 34 // PC2
#define UI_DISPLAY_D1_PIN 35 // PC3
#define UI_DISPLAY_D2_PIN 36 // PC4
#define UI_DISPLAY_D3_PIN 37 // PC5
#define UI_DISPLAY_D4_PIN 38 // PC6
#define UI_DISPLAY_D5_PIN 39 // PC7
#define UI_DISPLAY_D6_PIN 40 // PC8
#define UI_DISPLAY_D7_PIN 41 // PC9
#define SCK_PIN 42 // PA19
#define MOSI_PIN 43 // PA20
#define UI_DISPLAY_RW_PIN_NOT_USED 45 // PC18
#define SD_CARD_1 79 // PA24
#define SD_CARD_2 80 // PA23
#define SD_CARD_3 81 // PA22
#define TOP_SENSOR_PIN 64 // PB19
#define BEEPER_PIN 66 // PB15
#define HEATER_1_PIN 67 // PB16
#define ORIG_Y_MIN_PIN 68 // PA1
#define ORIG_Y_ENABLE_PIN 69 // PA0
#define RIGHT_JAM_SENSOR_PIN 70 // PA17
#define BUTTON_RIGHT 72 // PC30
#define SD_MISO_PIN 73 // PA21
#define SD_INSERTED 74 // PA25
#define UI_BACKLIGHT_PIN 78 // PB23
#define ORIG_FAN2_PIN 85 // PB11 -1
#define ORIG_Z_MIN_PIN 92 // PB21 -1
#define LEFT_JAM_SENSOR 108 // PC20 -1
#define CARTRIDGE_CHIP_1 115 // PB0 -1
#define CARTRIDGE_CHIP_2 116 // PB1 -1
#define Z_PROBE_PIN 117 // PB2 -1
#define ORIG_Z_DIR_PIN 118 // PB3 -1
#define ORIG_Z_STEP_PIN 119 // PB4 -1
#define ORIG_Z_ENABLE_PIN 120 // PB5 -1
#define ORIG_E0_DIR_PIN 121 // PB6 -1
#define ORIG_E0_STEP_PIN 122 // PB7 -1
#define ORIG_E0_ENABLE_PIN 123 // PB8 -1
#define UI_DISPLAY_ENABLE_PIN 125 // PB24 -1
#define Z_STOP 128 // PB22 -1
#define UI_DISPLAY_I2C_OUTPUT_PINS 65504


#define CASE_LIGHTS_PIN LIGHT_PIN
#define E0_DIR_PIN ORIG_E0_DIR_PIN
#define E0_ENABLE_PIN ORIG_E0_ENABLE_PIN
#define E0_STEP_PIN ORIG_E0_STEP_PIN
#define EXT0_DIR2_PIN E0_DIR_PIN
#define EXT0_DIR_PIN E0_DIR_PIN
#define EXT0_ENABLE2_PIN E0_ENABLE_PIN
#define EXT0_ENABLE_PIN E0_ENABLE_PIN
#define EXT0_EXTRUDER_COOLER_PIN ORIG_FAN_PIN
#define EXT0_HEATER_PIN HEATER_0_PIN
#define EXT0_STEP2_PIN E0_STEP_PIN
#define EXT0_STEP_PIN E0_STEP_PIN
#define EXT0_TEMPSENSOR_PIN TEMP_0_PIN
#define FAN2_PIN ORIG_FAN2_PIN
#define FAN_PIN ORIG_FAN2_PIN
#define HEATED_BED_HEATER_PIN HEATER_1_PIN
#define HEATED_BED_SENSOR_PIN TEMP_1_PIN
#define X_DIR_PIN ORIG_X_DIR_PIN
#define X_ENABLE_PIN ORIG_X_ENABLE_PIN
#define X_MIN_PIN ORIG_X_MIN_PIN
#define X_STEP_PIN ORIG_X_STEP_PIN
#define Y_DIR_PIN ORIG_Y_DIR_PIN
#define Y_ENABLE_PIN ORIG_Y_ENABLE_PIN
#define Y_MIN_PIN ORIG_Y_MIN_PIN
#define Y_STEP_PIN ORIG_Y_STEP_PIN
#define Z_DIR_PIN ORIG_Z_DIR_PIN
#define Z_ENABLE_PIN ORIG_Z_ENABLE_PIN
#define Z_MIN_PIN ORIG_Z_MIN_PIN
#define Z_STEP_PIN ORIG_Z_STEP_PIN



#define BED_ANALOG_CHANNEL ACCOMMA5 HEATED_BED_SENSOR_PIN
#define CASE_LIGHTS_PIN LIGHT_PIN
#define DIO0_PIN PIO_PA8A_URXD
#define DIO101_PIN PIO_PC27
#define DIO108_PIN PIO_PC20
#define DIO10_PIN PIO_PC29B_TIOB7
#define DIO117_PIN PIO_PB2A_ETX0
#define DIO118_PIN PIO_PB3A_ETX1
#define DIO119_PIN PIO_PB4A_ECRSDV
#define DIO11_PIN PIO_PD7B_TIOA8
#define DIO120_PIN PIO_PB5A_ERX0
#define DIO121_PIN PIO_PB6A_ERX1
#define DIO122_PIN PIO_PB7A_ERXER
#define DIO123_PIN PIO_PB8A_EMDC
#define DIO124_PIN PIO_PB9A_EMDIO
#define DIO125_PIN PIO_PB24
#define DIO12_PIN PIO_PD8B_TIOB8
#define DIO13_PIN PIO_PB27B_TIOB0
#define DIO14_PIN PIO_PD4B_TXD3
#define DIO15_PIN PIO_PD5B_RXD3
#define DIO16_PIN PIO_PA13A_TXD1
#define DIO17_PIN PIO_PA12A_RXD1
#define DIO18_PIN PIO_PA11A_TXD0
#define DIO19_PIN PIO_PA10A_RXD0
#define DIO1_PIN PIO_PA9A_UTXD
#define DIO20_PIN PIO_PB12A_TWD1
#define DIO21_PIN PIO_PB13A_TWCK1
#define DIO22_PIN PIO_PB26
#define DIO23_PIN PIO_PA14
#define DIO24_PIN PIO_PA15
#define DIO25_PIN PIO_PD0
#define DIO26_PIN PIO_PD1
#define DIO27_PIN PIO_PD2
#define DIO28_PIN PIO_PD3
#define DIO29_PIN PIO_PD6
#define DIO2_PIN PIO_PB25B_TIOA0
#define DIO30_PIN PIO_PD9
#define DIO31_PIN PIO_PA7
#define DIO32_PIN PIO_PD10
#define DIO33_PIN PIO_PC1
#define DIO34_PIN PIO_PC2
#define DIO35_PIN PIO_PC3
#define DIO36_PIN PIO_PC4
#define DIO37_PIN PIO_PC5
#define DIO38_PIN PIO_PC6
#define DIO39_PIN PIO_PC7
#define DIO3_PIN PIO_PC28B_TIOA7
#define DIO40_PIN PIO_PC8
#define DIO41_PIN PIO_PC9
#define DIO42_PIN PIO_PA19
#define DIO43_PIN PIO_PA20
#define DIO44_PIN PIO_PC19
#define DIO45_PIN PIO_PC18
#define DIO46_PIN PIO_PC17
#define DIO47_PIN PIO_PC16
#define DIO48_PIN PIO_PC15
#define DIO49_PIN PIO_PC14
#define DIO4_PIN PIO_PC26B_TIOB6
#define DIO50_PIN PIO_PC13
#define DIO51_PIN PIO_PC12
#define DIO52_PIN PIO_PB21
#define DIO53_PIN PIO_PB14
#define DIO54_PIN PIO_PA16X1_AD7
#define DIO55_PIN PIO_PA24X1_AD6
#define DIO56_PIN PIO_PA23X1_AD5
#define DIO57_PIN PIO_PA22X1_AD4
#define DIO58_PIN PIO_PA6X1_AD3
#define DIO59_PIN PIO_PA4X1_AD2
#define DIO5_PIN PIO_PC25B_TIOA6
#define DIO60_PIN PIO_PA3X1_AD1
#define DIO61_PIN PIO_PA2X1_AD0
#define DIO62_PIN PIO_PB17X1_AD10
#define DIO63_PIN PIO_PB18X1_AD11
#define DIO64_PIN PIO_PB19X1_AD12
#define DIO65_PIN PIO_PB20X1_AD13
#define DIO66_PIN PIO_PB15X1_DAC0
#define DIO67_PIN PIO_PB16X1_DAC1
#define DIO68_PIN PIO_PA1A_CANRX0
#define DIO69_PIN PIO_PA0A_CANTX0
#define DIO6_PIN PIO_PC24B_PWML7
#define DIO70_PIN PIO_PA17A_TWD0
#define DIO71_PIN PIO_PA18A_TWCK0
#define DIO72_PIN PIO_PC30
#define DIO73_PIN PIO_PA21
#define DIO74_PIN PIO_PA25A_SPI0_MISO
#define DIO75_PIN PIO_PA26A_SPI0_MOSI
#define DIO76_PIN PIO_PA27A_SPI0_SPCK
#define DIO77_PIN PIO_PA28A_SPI0_NPCS0
#define DIO78_PIN PIO_PB23B_SPI0_NPCS3
#define DIO79_PIN PIO_PA17A_TWD0|PIO_PA18A_TWCK0
#define DIO7_PIN PIO_PC23B_PWML6
#define DIO80_PIN PIO_PB12A_TWD1|PIO_PB13A_TWCK1
#define DIO81_PIN PIO_PA8A_URXD|PIO_PA9A_UTXD
#define DIO82_PIN PIO_PA11A_TXD0|PIO_PA10A_RXD0
#define DIO83_PIN PIO_PA13A_TXD1|PIO_PA12A_RXD1
#define DIO84_PIN PIO_PD4B_TXD3|PIO_PD5B_RXD3
#define DIO85_PIN PIO_PB11A_UOTGID
#define DIO86_PIN PIO_PB21B_SPI0_NPCS2
#define DIO87_PIN PIO_PA29A_SPI0_NPCS1
#define DIO88_PIN PIO_PB15A_CANRX1
#define DIO89_PIN PIO_PB14A_CANTX1
#define DIO8_PIN PIO_PC22B_PWML5
#define DIO90_PIN PIO_PA1A_CANRX0|PIO_PA0A_CANTX0
#define DIO91_PIN PIO_PB15A_CANRX1|PIO_PB14A_CANTX1
#define DIO92_PIN PIO_PB22
#define DIO93_PIN PIO_PB10
#define DIO9_PIN PIO_PC21B_PWML4
#define E0_DIR_PIN ORIG_E0_DIR_PIN
#define E0_ENABLE_PIN ORIG_E0_ENABLE_PIN
#define E0_PINS ORIG_E0_STEP_PIN,ORIG_E0_DIR_PIN,ORIG_E0_ENABLE_PIN,
#define E0_STEP_PIN ORIG_E0_STEP_PIN
#define E1_DIR_PIN ORIG_E1_DIR_PIN
#define E1_ENABLE_PIN ORIG_E1_ENABLE_PIN
#define E1_PINS ORIG_E1_STEP_PIN,ORIG_E1_DIR_PIN,ORIG_E1_ENABLE_PIN,
#define E1_STEP_PIN ORIG_E1_STEP_PIN
#define E2_DIR_PIN ORIG_E2_DIR_PIN
#define E2_ENABLE_PIN ORIG_E2_ENABLE_PIN
#define E2_PINS
#define E2_STEP_PIN ORIG_E2_STEP_PIN
#define E3_DIR_PIN ORIG_E3_DIR_PIN
#define E3_ENABLE_PIN ORIG_E3_ENABLE_PIN
#define E3_STEP_PIN ORIG_E3_STEP_PIN
#define E4_DIR_PIN ORIG_E4_DIR_PIN
#define E4_ENABLE_PIN ORIG_E4_ENABLE_PIN
#define E4_STEP_PIN ORIG_E4_STEP_PIN
#define E5_DIR_PIN ORIG_E5_DIR_PIN
#define E5_ENABLE_PIN ORIG_E5_ENABLE_PIN
#define E5_STEP_PIN ORIG_E5_STEP_PIN
#define ENABLED_ADC_CHANNELS {TEMP_0_PIN, TEMP_1_PIN, TEMP_2_PIN}
#define EXT0_ANALOG_CHANNEL EXT0_TEMPSENSOR_PIN
#define EXT0_DIR2_PIN E0_DIR_PIN
#define EXT0_DIR_PIN E0_DIR_PIN
#define EXT0_ENABLE2_PIN E0_ENABLE_PIN
#define EXT0_ENABLE_PIN E0_ENABLE_PIN
#define EXT0_EXTRUDER_COOLER_PIN ORIG_FAN_PIN
#define EXT0_HEATER_PIN HEATER_0_PIN
#define EXT0_STEP2_PIN E0_STEP_PIN
#define EXT0_STEP_PIN E0_STEP_PIN
#define EXT0_TEMPSENSOR_PIN TEMP_0_PIN
#define EXT1_DIR2_PIN E0_DIR_PIN
#define EXT1_DIR_PIN E1_DIR_PIN
#define EXT1_ENABLE2_PIN E0_ENABLE_PIN
#define EXT1_ENABLE_PIN E1_ENABLE_PIN
#define EXT1_HEATER_PIN HEATER_2_PIN
#define EXT1_SENSOR_INDEX EXT1_TEMPSENSOR_PIN
#define EXT1_STEP2_PIN E0_STEP_PIN
#define EXT1_STEP_PIN E1_STEP_PIN
#define EXT1_TEMPSENSOR_PIN TEMP_2_PIN
#define EXT2_SENSOR_INDEX EXT2_TEMPSENSOR_PIN
#define EXT3_SENSOR_INDEX EXT3_TEMPSENSOR_PIN
#define EXT4_SENSOR_INDEX EXT4_TEMPSENSOR_PIN
#define EXT5_SENSOR_INDEX EXT5_TEMPSENSOR_PIN
#define FAN2_PIN ORIG_FAN2_PIN
#define FAN_PIN ORIG_FAN2_PIN
#define HEATED_BED_HEATER_PIN HEATER_1_PIN
#define HEATED_BED_SENSOR_PIN TEMP_1_PIN
#define PS_ON_PIN ORIG_PS_ON_PIN
#define X2_DIR_PIN E1_DIR_PIN
#define X2_ENABLE_PIN E1_ENABLE_PIN
#define X2_STEP_PIN E1_STEP_PIN
#define X_DIR_PIN ORIG_X_DIR_PIN
#define X_ENABLE_PIN ORIG_X_ENABLE_PIN
#define X_MAX_PIN ORIG_X_MAX_PIN
#define X_MIN_PIN ORIG_X_MIN_PIN
#define X_STEP_PIN ORIG_X_STEP_PIN
#define Y2_DIR_PIN E1_DIR_PIN
#define Y2_ENABLE_PIN E1_ENABLE_PIN
#define Y2_STEP_PIN E1_STEP_PIN
#define Y_DIR_PIN ORIG_Y_DIR_PIN
#define Y_ENABLE_PIN ORIG_Y_ENABLE_PIN
#define Y_MAX_PIN ORIG_Y_MAX_PIN
#define Y_MIN_PIN ORIG_Y_MIN_PIN
#define Y_STEP_PIN ORIG_Y_STEP_PIN
#define Z2_DIR_PIN E1_DIR_PIN
#define Z2_ENABLE_PIN E1_ENABLE_PIN
#define Z2_STEP_PIN E1_STEP_PIN
#define Z3_DIR_PIN E2_DIR_PIN
#define Z3_ENABLE_PIN E2_ENABLE_PIN
#define Z3_STEP_PIN E2_STEP_PIN
#define Z_DIR_PIN ORIG_Z_DIR_PIN
#define Z_ENABLE_PIN ORIG_Z_ENABLE_PIN
#define Z_MAX_PIN ORIG_Z_MAX_PIN
#define Z_MIN_PIN ORIG_Z_MIN_PIN
#define Z_STEP_PIN ORIG_Z_STEP_PIN
