//this is derived from the ConfigurationA.i file
// pin names derived from 144-lead LQFP SAM3X4/8E Pinout datasheet and
// arduino pin mapping and the repetier xlsx sheet
#define SYSTEM_FAN 4 // PC26
#define UI_DISPLAY_RS_PIN 8 // PC22
#define BUTTON_DOWN 10 // PC29 
#define ORIG_X_MIN_PIN 11 // PD7
#define ORIG_Y_DIR_PIN 12 // PD8
#define AMBER_LED 13 // PB27
#define ORIG_X_DIR_PIN 14 // PD4
#define ORIG_X_STEP_PIN 15 // PD5
#define HEATER_0_PIN 16 // PA13
#define LIGHT_PIN 17 // PA12
#define FIL_SENSOR1_PIN 24 // PA15
#define ORIG_FAN_PIN 25 // PD0
#define ORIG_X_ENABLE_PIN 29 // PD6
#define ORIG_Y_STEP_PIN 30 // PD9
#define UI_DISPLAY_D0_PIN 34 // PC2
#define UI_DISPLAY_D1_PIN 35 // PC3
#define UI_DISPLAY_D2_PIN 36 // PC4
#define UI_DISPLAY_D3_PIN 37 // PC5
#define UI_DISPLAY_D4_PIN 38 // PC6
#define UI_DISPLAY_D5_PIN 39 // PC7
#define UI_DISPLAY_D6_PIN 40 // PC8
#define UI_DISPLAY_D7_PIN 41 // PC9
#define SCK_PIN 42 // PA19
#define MOSI_PIN 43 // PA20
#define BUTTON_UP 44 // PC19 
#define UI_DISPLAY_RW_PIN_NOT_USED 45 // PC18
#define TEMP_0_PIN 65 // PB20 ADC13
#define TEMP_1_PIN 126(52) // PB21 ADC14
#define TOP_SENSOR_PIN 64 // PB19
#define BEEPER_PIN 66 // PB15
#define HEATER_1_PIN 67 // PB16
#define ORIG_Y_MIN_PIN 68 // PA1
#define ORIG_Y_ENABLE_PIN 69 // PA0
#define RIGHT_JAM_SENSOR_PIN 70 // PA17
#define BUTTON_RIGHT 72 // PC30 
#define BUTTON_LEFT 75 // PA26 
#define BUTTON_SELECT 76 // PA27 
#define BUTTON_HOME 77 // PA28 
#define SD_MISO_PIN 73 // PA21
#define SD_INSERTED 74 // PA25
#define UI_BACKLIGHT_PIN 78 // PB23
#define SD_CARD_1 79 // PA24
#define SD_CARD_2 80 // PA23
#define SD_CARD_3 81 // PA22
#define ORIG_FAN2_PIN 85 // PB11 -1
#define ORIG_Z_MIN_PIN 92 // PB22 -1
#define LEFT_JAM_SENSOR 108 // PC20 -1
#define CARTRIDGE_CHIP_1 115 // PB0 -1
#define CARTRIDGE_CHIP_2 116 // PB1 -1
#define Z_PROBE_PIN 117 // PB2 -1
#define ORIG_Z_DIR_PIN 118 // PB3 -1
#define ORIG_Z_STEP_PIN 119 // PB4 -1
#define ORIG_Z_ENABLE_PIN 120 // PB5 -1
#define ORIG_E0_DIR_PIN 121 // PB6 -1
#define ORIG_E0_STEP_PIN 122 // PB7 -1
#define ORIG_E0_ENABLE_PIN 123 // PB8 -1
#define UI_DISPLAY_ENABLE_PIN 125 // PB24 -1
#define Z_STOP 128 // PB22 -1
#define UI_DISPLAY_I2C_OUTPUT_PINS 65504


#define CASE_LIGHTS_PIN LIGHT_PIN
#define E0_DIR_PIN ORIG_E0_DIR_PIN
#define E0_ENABLE_PIN ORIG_E0_ENABLE_PIN
#define E0_STEP_PIN ORIG_E0_STEP_PIN
#define EXT0_DIR2_PIN E0_DIR_PIN
#define EXT0_DIR_PIN E0_DIR_PIN
#define EXT0_ENABLE2_PIN E0_ENABLE_PIN
#define EXT0_ENABLE_PIN E0_ENABLE_PIN
#define EXT0_EXTRUDER_COOLER_PIN ORIG_FAN_PIN
#define EXT0_HEATER_PIN HEATER_0_PIN
#define EXT0_STEP2_PIN E0_STEP_PIN
#define EXT0_STEP_PIN E0_STEP_PIN
#define EXT0_TEMPSENSOR_PIN TEMP_0_PIN
#define FAN2_PIN ORIG_FAN2_PIN
#define FAN_PIN ORIG_FAN2_PIN
#define HEATED_BED_HEATER_PIN HEATER_1_PIN
#define HEATED_BED_SENSOR_PIN TEMP_1_PIN
#define X_DIR_PIN ORIG_X_DIR_PIN
#define X_ENABLE_PIN ORIG_X_ENABLE_PIN
#define X_MIN_PIN ORIG_X_MIN_PIN
#define X_STEP_PIN ORIG_X_STEP_PIN
#define Y_DIR_PIN ORIG_Y_DIR_PIN
#define Y_ENABLE_PIN ORIG_Y_ENABLE_PIN
#define Y_MIN_PIN ORIG_Y_MIN_PIN
#define Y_STEP_PIN ORIG_Y_STEP_PIN
#define Z_DIR_PIN ORIG_Z_DIR_PIN
#define Z_ENABLE_PIN ORIG_Z_ENABLE_PIN
#define Z_MIN_PIN ORIG_Z_MIN_PIN
#define Z_STEP_PIN ORIG_Z_STEP_PIN


#define CASE_LIGHTS_PIN LIGHT_PIN
#define E0_DIR_PIN ORIG_E0_DIR_PIN
#define E0_ENABLE_PIN ORIG_E0_ENABLE_PIN
#define E0_STEP_PIN ORIG_E0_STEP_PIN
#define ENABLED_ADC_CHANNELS {TEMP_0_PIN, TEMP_1_PIN}
#define EXT0_ANALOG_CHANNEL EXT0_TEMPSENSOR_PIN
#define EXT0_DIR2_PIN E0_DIR_PIN
#define EXT0_DIR_PIN E0_DIR_PIN
#define EXT0_ENABLE2_PIN E0_ENABLE_PIN
#define EXT0_ENABLE_PIN E0_ENABLE_PIN
#define EXT0_EXTRUDER_COOLER_PIN ORIG_FAN_PIN
#define EXT0_HEATER_PIN HEATER_0_PIN
#define EXT0_STEP2_PIN E0_STEP_PIN
#define EXT0_STEP_PIN E0_STEP_PIN
#define EXT0_TEMPSENSOR_PIN TEMP_0_PIN
#define FAN2_PIN ORIG_FAN2_PIN
#define FAN_PIN ORIG_FAN2_PIN
#define HEATED_BED_HEATER_PIN HEATER_1_PIN
#define HEATED_BED_SENSOR_PIN TEMP_1_PIN
#define PS_ON_PIN ORIG_PS_ON_PIN
#define X_DIR_PIN ORIG_X_DIR_PIN
#define X_ENABLE_PIN ORIG_X_ENABLE_PIN
#define X_MAX_PIN ORIG_X_MAX_PIN
#define X_MIN_PIN ORIG_X_MIN_PIN
#define X_STEP_PIN ORIG_X_STEP_PIN
#define Y_DIR_PIN ORIG_Y_DIR_PIN
#define Y_ENABLE_PIN ORIG_Y_ENABLE_PIN
#define Y_MAX_PIN ORIG_Y_MAX_PIN
#define Y_MIN_PIN ORIG_Y_MIN_PIN
#define Y_STEP_PIN ORIG_Y_STEP_PIN
#define Z_DIR_PIN ORIG_Z_DIR_PIN
#define Z_ENABLE_PIN ORIG_Z_ENABLE_PIN
#define Z_MAX_PIN ORIG_Z_MAX_PIN
#define Z_MIN_PIN ORIG_Z_MIN_PIN
#define Z_STEP_PIN ORIG_Z_STEP_PIN
